# SPDX-FileCopyrightText: © 2026 OpenCHAMI a Series of LF Projects, LLC
# SPDX-License-Identifier: MIT
name: REUSE Compliance Check

on: [push, pull_request]
jobs:
  reuse:
    permissions:
      contents: read
    uses: OpenCHAMI/github-actions/.github/workflows/reuse.yml@8143942058adef1ce81a96a11ae9074358df4fbd # v3.11
