# SPDX-FileCopyrightText: © 2026 OpenCHAMI a Series of LF Projects, LLC
# SPDX-License-Identifier: MIT

# This workflow uses actions that are not certified by GitHub. They are
# provided by a third-party and are governed by separate terms of
# service, privacy policy, and support documentation.

name: scorecard
on:
  branch_protection_rule:
  schedule:
    - cron: '39 5 * * 1'
  push:
    branches: [main]
  pull_request:

jobs:
  scorecard:
    permissions:
      contents: read
      security-events: write
      id-token: write
    uses: OpenCHAMI/github-actions/.github/workflows/scorecard.yml@8143942058adef1ce81a96a11ae9074358df4fbd # v3.11
